version: '3.8'

services:
  web:
    build: .
    image: vinted-downloader-web
    container_name: vinted-downloader
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
